# Generated by Django 2.2.4 on 2019-09-03 21:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snippets', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('github_account', models.SlugField(max_length=255, unique=True)),
                ('rating', models.FloatField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('first_commit', models.DateField()),
                ('skills', models.ManyToManyField(related_name='competent_users', to='skills.Skill')),
                ('snippets', models.ManyToManyField(related_name='users_added', to='snippets.Snippet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_code_from_date', models.DateField()),
                ('review_projects', models.ManyToManyField(to='skills.GithubProject')),
                ('review_skills', models.ManyToManyField(to='skills.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
