# Generated by Django 2.2.4 on 2019-09-15 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('skills', '0001_initial'),
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('github_account', models.URLField(max_length=255, unique=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_indexation_date', models.DateField(auto_now_add=True)),
                ('first_commit', models.DateField(auto_now_add=True)),
                ('github_projects', models.ManyToManyField(related_name='committers', to='projects.GithubProject')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('skills', models.ManyToManyField(related_name='competent_users', to='skills.SkillRating')),
                ('snippets', models.ManyToManyField(related_name='users_added', to='snippets.Snippet')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'programmer',
                'verbose_name_plural': 'programmers',
            },
            managers=[
                ('objects', users.managers.ProgrammerManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_code_from_date', models.DateField()),
                ('review_projects', models.ManyToManyField(to='projects.GithubProject')),
                ('review_skills', models.ManyToManyField(to='skills.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
