# Generated by Django 2.2.4 on 2019-09-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmer',
            name='github_account',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
