# Generated by Django 2.2.4 on 2019-09-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190903_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmer',
            name='first_commit',
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='rating',
        ),
        migrations.AlterField(
            model_name='programmer',
            name='skills',
            field=models.ManyToManyField(related_name='competent_users', to='skills.SkillRating'),
        ),
    ]
