# Generated by Django 2.2.4 on 2019-09-06 05:19

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190905_0628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmer',
            options={'verbose_name': 'programmer', 'verbose_name_plural': 'programmers'},
        ),
        migrations.AlterModelManagers(
            name='programmer',
            managers=[
                ('objects', users.managers.ProgrammerManager()),
            ],
        ),
    ]
