# Generated by Django 2.2.4 on 2019-09-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190906_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
