# Generated by Django 2.2.4 on 2019-09-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_programmer_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
