# Generated by Django 2.2.4 on 2019-09-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_programmer_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmer',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
