# Generated by Django 2.2.4 on 2019-09-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190906_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmer',
            name='is_admin',
        ),
    ]
