# Generated by Django 2.2.4 on 2019-09-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_programmer_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
