# Generated by Django 2.2.4 on 2019-09-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_programmer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmer',
            name='email',
        ),
    ]
