# Generated by Django 2.2.4 on 2019-09-08 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skillrating'),
        ('users', '0012_remove_programmer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='first_commit',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmer',
            name='github_projects',
            field=models.ManyToManyField(related_name='committers', to='skills.GithubProject'),
        ),
        migrations.AddField(
            model_name='programmer',
            name='last_indexation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
